### ISSUE TITLE
gitinspector crashes with not being able to encode a unicode character

### ISSUE THREAD

**Issue by Sermus** [ejwa/gitinspector#103]
For me it crashes when it's invoked with 
python.exe gitinspector.py -lr --format=html --file-types=c,cpp,cs,csproj,sln,sql,xaml,asmx,config,dbml,publishsettigs,bat,settings,cmd,csdef,vcxproj,saproj -x Reference,.designer.cs,GMap.NET,GlobalExpert,onvifcombined,Xmpp -l ../Code/ForestGuard  1>statJan2016.html

The symptom is:

Exception in thread Thread-2993:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "D:\Tools\gitinspector\gitinspector\blame.py", line 94, in run
    git_blame_r = subprocess.Popen(self.blame_command, bufsize=1, stdout=subprocess.PIPE).stdout
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0421' in position 96: ordinal not in range(128)

**Comment by adam-waldenberg** [comment]
Hi.

Your terminal is probably set to standard ASCII. This is already covered in the [FAQ (https://github.com/ejwa/gitinspector/wiki/FAQ).
This is most likely related to the terminal and not gitinspector directly. See issues #9, #19 and #54 for previous discussions on this. There are also a few other issues that cover this.

Please report if any of the above fixes the issue.

**Comment by Sermus** [comment]
Yes, you're right. Sorry for not reading FAQ section thoroughly enough.

2016-01-28 12:14 GMT+03:00 Adam Waldenberg <notifications@github.com>:

**Comment by adam-waldenberg** [comment]
@Sermus 

No worries. Great to hear that it's working. Marking as invalid and closing.
