### ISSUE TITLE
Aliasing/combining Git user names

### ISSUE THREAD

**Issue by Subject22** [ejwa/gitinspector#105]
Some Git users (especially new ones) make the mistake of setting their Git username to different values on different development machines. This leads to apparently fragmented contributions in GitInspectors output. 

Is there a way to to tell GitInspector to combine contributions for a collection of user names and treat them as the same contributor? If not, could this please be treated as a feature request 😊

**Comment by adam-waldenberg** [comment]
Hi.

Yes there is. Git itself has a fix for this. Please refer to the  [FAQ](https://github.com/ejwa/gitinspector/wiki/FAQ). First question at the top.

**Comment by Subject22** [comment]
Ah! Thank you very much! Sorry about that. I appreciate the help.

**Comment by adam-waldenberg** [comment]
Glad to help.
