### ISSUE TITLE
Support for Razor .cshtml files

### ISSUE THREAD

**Issue by SirMartin** [ejwa/gitinspector#107]
It can be very nice, to increment the support to .Net languages, include .cshtml files to the stats.

**Comment by adam-waldenberg** [comment]
Hi. This is nothing I have ever used. As I'm not comfortable with it, somebody that is will have to add the support for it. Pull requests are welcome. I'll leave this open for now.

**Comment by adam-waldenberg** [comment]
No feedbacj received concerning this, so closing.
