### ISSUE TITLE
Better documentation of "percentage_in_comments" and "age"?

### ISSUE THREAD

**Issue by tosone** [ejwa/gitinspector#111]
I generate a json file. But I do not know that as the title said. Could you help me?

```
{
  "name": "Gen Liu",
  "email": "Tom@bob.cc",
  "gravatar": "https://www.gravatar.com/avatar/e49a8987d1c411d30191e4ba7c439b70?default=identicon",
  "rows": 836,
  "stability": 63.7,
  "age": 5.1,
  "percentage_in_comments": 3.83
}
```

**Comment by adam-waldenberg** [comment]
Yes. Of course. It means that 3.83% of all Gen Liu's rows can be found inside comments - the rest is real code.

Age is the average age (in months) of all the rows that the user has written. This can also be shown in weeks of the "-w" flag has been specified.

I can also mention that the stability value tells you that 63.7% of all the code that Gen has ever written has survived up until now.

/ Adam Waldenberg

**Comment by tosone** [comment]
This tool is realy nice. A better dashboard to show this data is needed.

**Comment by adam-waldenberg** [comment]
Thank you. Yes, gitinspector is really useful when probing an authors activity within a project. As it is now, the nicest output available is the HTML one. A new repsonsive HTML output is currently in the works and can be followed here; the https://github.com/ejwa/gitinspector/tree/issue/28 and in issue #28.

When I have time to actually finish this is another question though :). In any case, pull requests are accepted and appreciated if anyone is willing to help.

**Comment by banbar** [comment]
What could a stability value of 843.6 may mean? 
At the timeline, I have observed that there are activity spanning more than four weeks, but the Age the value is less than 1. How could that be?
For each developer, timeline has two colors: presumably, claret red represents deletions and green additions - is that so?

**Comment by adam-waldenberg** [comment]
@banbar A stability value over 100 means that more rows have been attributed to an author than he has actually inserted (in the case of 843 - more than 8 times more). This can happen if some other developer for example inserts duplicate code that git attributes to the original author.

Red is deletion and green is insertions - correct.

Age is the average age of the *remaining rows* that a certain author has in the repository. Basically its looks at the age of all the remaining rows blamed by git to a specific author.
