### ISSUE TITLE
Available alternatives

### ISSUE THREAD

**Issue by techtonik** [ejwa/gitinspector#130]
Is there any list of open source projects that provide the same functionality? I am looking to gathers stats on Mercurial commit size, which `gitinspector` doesn't provide, unfortunately.

**Comment by adam-waldenberg** [comment]
@techtonik If you need to analyze a mercurial project, you can use https://github.com/frej/fast-export, to first convert your repo to a git repository for analysis.

There's https://labs.freehackers.org/projects/hgactivity, but apart from that I don't know of any mercurial specific tools.

**Comment by techtonik** [comment]
https://labs.freehackers.org/projects/hgactivity/wiki gives better picture. I also found https://bitbucket.org/mg/hgchart/wiki/Home

Anyway, some awesome page linking to all such tools would be awesome. There is also http://statcvs.sourceforge.net/ and http://statsvn.org/ with nice graphs that could probably be reused.

**Comment by adam-waldenberg** [comment]
Right. I won't be linking to other projects - I think there are better places for such lists. It also needs to be said that while there are many projects that gather commit statistics from different kinds of repositories, gitinspector has a very specific design goal and use case - something that those projects don't share. This is why it got created in the first place. See https://github.com/ejwa/gitinspector/wiki/Contributing#what-to-consider-when-writing-code-for-new-statistics.

**Comment by techtonik** [comment]
I don't know any better place for such list. If you know one - tell me.

**Comment by adam-waldenberg** [comment]
There are many discussions on Stackoverflow concerning this, for example;
http://stackoverflow.com/questions/9282346/tortoisehg-mercurial-project-statistics-and-reports/9283466#9283466

There are also a few more extensions on the mercurial wiki;
https://www.mercurial-scm.org/wiki/UsingExtensions

Those are the first that comes to mind. Maybe it would also be possible to get a list of software onto wikipedia. Similar lists exist for other software branches, so why not repo statistics as well. I'm guessing that nobody has taken the time to make such a list yet.

**Comment by techtonik** [comment]
Wikipedia may remove lists that are non-significant, so nobody wants to invest time in that. It also needs references in media for every piece of software. There was attempt to remove Spyder IDE page, so I doubt that any lesser tool has much chance to survive there.

**Comment by adam-waldenberg** [comment]
Hi @techtonik. A private page for each tool is probably senseless and would get removed, yes. However, it might work to add a list such as one of these;

https://en.wikipedia.org/wiki/Category:Lists_of_software

**Comment by techtonik** [comment]
Links without primary page are also get remove from those lists. I had multiple IRC software link removed due to this reason.
