### ISSUE TITLE
Enhancement suggestion - merge git authors?

### ISSUE THREAD

**Issue by willend** [ejwa/gitinspector#131]
Hi there,

I am analysing a reasonably old code with a long history (~18 years through rcs->CVS->SVN->git revision control) - and hence several commit authors had different identifiers along the way...

I tried looking through the docs and didn't find anything along the lines of merging stats from multiple authors under the same ID - but I would personally find it really useful.

Best,
Peter Willendrup

**Comment by adam-waldenberg** [comment]
@willend,

This is already available, please refer to the [FAQ](https://github.com/ejwa/gitinspector/wiki/FAQ). When it comes to ID's from SVN repos, there might be a few problems, however git has solutions for this when [migrating repos](https://git-scm.com/book/it/v2/Git-and-Other-Systems-Migrating-to-Git).

I think you should be able to merge with .mailmap, but if problems arise you can also [rewrite the author info](https://help.github.com/articles/changing-author-info).

**Comment by adam-waldenberg** [comment]
Hi @willend . Did you manage to resolve this somehow?

**Comment by willend** [comment]
I think I did eventually manage or find a different solution, thanks! :-)
