### ISSUE TITLE
Global stats

### ISSUE THREAD

**Issue by tetraf** [ejwa/gitinspector#137]
It may be nice to report total number of lines/files/commits/authors and their average by day/week/month/year (even with time graphs and punch card), some data like [sloccount](http://www.dwheeler.com/sloccount/) and other global stats.

**Comment by adam-waldenberg** [comment]
It might be nice. However, I'm not that crazy about adding stats that don't really help when evaluating each author.

**Comment by adam-waldenberg** [comment]
Closing this, as I don't really consider this as a fit for the use case of gitinspector.
