### ISSUE TITLE
Add a way to merge authors

### ISSUE THREAD

**Issue by JalilArfaoui** [ejwa/gitinspector#151]
During the lifetime of a project, a single author may have used different emails in his commits, and different display names ... 

It would be great to have the option of merging different detected authors into a single one. 

For example, I have a project where I can see in authors "Jalil Arfaoui", "Jalil ARFAOUI" and "jarfaoui". 

If I could have and option to specify a mapping for exemple, either in command line of via a config file : 

```
gitinspector -A "Jalil ARFAOUI":"Jalil Arfaoui","jarfaoui": "Jalil Arfaoui"
```

Or via a `.gitinspector` file : 

```
{
  "authors": {
    "mapping": {
      "Jalil ARFAOUI": "Jalil Arfaoui",
      "jarfaoui": "Jalil Arfaoui",
   }
}
```

**Comment by adam-waldenberg** [comment]
Hi @JalilArfaoui.

There is no need for this in gitinspector. It's already an integral feature of GIT. It's also covered in the [FAQ](https://github.com/ejwa/gitinspector/wiki/FAQ).

Please also refer to issue #105.

**Comment by JalilArfaoui** [comment]
Oh I didn't know about .mailmap file ! This is so cool

Thank you @adam-waldenberg !

Sorry for the unneeded issue
