### ISSUE TITLE
Multi branch analysis

### ISSUE THREAD

**Issue by mensfeld** [ejwa/gitinspector#152]
It would be cool if we could analyze all the branches. ~~I believe, that it would require only a small change (ofc this would have to be a flag, so bigger changes in general)~~ won't be as easy as I thought as the blame won't work but still I believe that this would be a valuable feature:

```python
git_log_r = subprocess.Popen(filter(None, ["git", "log", "--reverse", "--pretty=%ct|%cd|%H|%aN|%aE"

# to 
it_log_r = subprocess.Popen(filter(None, ["git", "log", "--all", "--reverse", "--pretty=%ct|%cd|%H|%aN|%aE"
```

**Comment by adam-waldenberg** [comment]
Hi @mensfeld. This is planned, but in a more fine-grained way - allowing to specify branches directly when specifying a repo. See #92. The plan is to allow wildcards and/or regexps to match multiple repos and branches.

**Comment by mensfeld** [comment]
Hey @adam-waldenberg  thank you. I'm looking forward to it!
