### ISSUE TITLE
Multiple GIT repositories

### ISSUE THREAD

**Issue by rohits-page** [ejwa/gitinspector#155]
I am having issues running gitinspector over multiple repositories. How do I run gitinspector over multiple repositories and get a comprehensive view of developer activity?

Thanks!

**Comment by adam-waldenberg** [comment]
Hi @rohits-page. You just specify the relative or absolute path on the command line to each repository. Gitinspector will then merge these together into a report.

**Comment by rohits-page** [comment]
Thanks. So if I have 100 repositories, do I specify all 500 entries?
Is there a way to specify the root folder and let the script identify the
repositories?
Will it be possible for you to share an example?

Thanks

**Comment by adam-waldenberg** [comment]
@rohits-page 

No, there is no recursion. Implementing recursion would probably introduce unforeseen side-effects. If you want to check 100 repos, you need to specify all of them. You can always make a script to take care of the recursion if you like.

The merging is somewhat explained if you specify "--help" and read the documentation (or in the man page) - basically, you just do,

gitinspector <options> [repo1] [repo2] [repo3]...
