### ISSUE TITLE
Stats about most edited files

### ISSUE THREAD

**Issue by gonzobrains** [ejwa/gitinspector#157]
Is there a way to get stats to show the most heavily-used/committed files?  I'd like to use this tool to help me better understand inherited codebases.

**Comment by mensfeld** [comment]
@gonzobrains => git effort

**Comment by adam-waldenberg** [comment]
Hi @gonzobrains. Not implemented - but something similar has been discussed and is planned for a future release. See issue #135. Closing this as a duplicate.
