### ISSUE TITLE
Allow equivalencing git users

### ISSUE THREAD

**Issue by MrMichaelJKelly** [ejwa/gitinspector#159]
People often use multiple aliases in Git projects.  Allow having a config file that associates multiple commit names as one person and gives the preferred ID to use.

**Comment by adam-waldenberg** [comment]
Hi @MrMichaelJKelly. Would be senseless to implement, as it is already built into git. Please refer to the [FAQ](/ejwa/gitinspector/wiki/FAQ) for more information.

Closing.
