### ISSUE TITLE
Link to github usernames and avatars

### ISSUE THREAD

**Issue by josemvidal** [ejwa/gitinspector#164]
In [my fork](https://github.com/josemvidal/gitinspector/tree/github-usernames) I added a `--github file.csv` paramater, where `file.csv` contains two columns: the first one with email addresses and the second one with github usernames.

The html output will then include the committer's github avatar, username, and profile link.

This is useful to me as all my students use github repos and I spend most of my time at github, so it is nice to see the same avatars I am used to.

I do not know if you will want this, or if using a file.csv was the best way to make this mapping. Having one file works for me because I have many repos to deal with, but only 1 spreadsheet with everyone's email and github username.

I'd be happy to make a pull-request if you want, or make further changes if needed.

**Comment by adam-waldenberg** [comment]
Hi @josemvidal. This might be interesting. It would have to support all output types that the gravatar module supports, though. If I recall correctly - XML, JSON and HTML all support avatars.

**Comment by josemvidal** [comment]
Makes sense. I'll work on it.
