### ISSUE TITLE
decode() argument 1 must be string, not None

### ISSUE THREAD

**Issue by varun7447** [ejwa/gitinspector#168]
Getting this error when running from Jenkins Shell command

```
+ /usr/lib/node_modules/gitinspector/gitinspector.py <<Repository Path>>>
Traceback (most recent call last):
  File "/usr/lib/node_modules/gitinspector/gitinspector.py", line 24, in <module>
    gitinspector.main()
  File "/usr/lib/node_modules/gitinspector/gitinspector/gitinspector.py", line 131, in main
    argv = terminal.convert_command_line_to_utf8()
  File "/usr/lib/node_modules/gitinspector/gitinspector/terminal.py", line 122, in convert_command_line_to_utf8
    argv.append(arg.decode(sys.stdin.encoding, "replace"))
TypeError: decode() argument 1 must be string, not None
```

**Comment by MichaelKaaden** [comment]
@varun7447 Setting the environment variable PYTHONIOENCODING should fix your problem. Please give it a try!

**Comment by varun7447** [comment]
What should be the encoding set to?

**Comment by MichaelKaaden** [comment]
That depends. I like using UTF-8.

**Comment by Art4** [comment]
I had the same issue. Using `env PYTHONIOENCODING=utf-8 gitinspector.py ...` works for me.

**Comment by adam-waldenberg** [comment]
This is an old issue already discussed related to Python and invalid terminal encodings. See for example #19. Not a gitinspector issue.

Closing

**Comment by Art4** [comment]
I think it is worth to document this issue in the wiki.

**Comment by adam-waldenberg** [comment]
@Art4 It kinda already is mentioned in the FAQ. However it  uses UnicodeEncodeError exception as an example, which is related. Same issue, but a different exception. It all comes down to a terminal that can't handle the characters.

In this instance it just happens earlier because sys.stdin.encoding is set to None.
