### ISSUE TITLE
Graph does not print

### ISSUE THREAD

**Issue by saya327** [ejwa/gitinspector#173]
I installed gitinspect and called pathfontexpathfile to print the report. But Graph does not print
Graph must be in report.  need help.
![1](https://user-images.githubusercontent.com/7323970/37380048-1233da40-277a-11e8-868d-93ef07a68db8.png)

**Comment by adam-waldenberg** [comment]
I am not sure what you are trying to do? Gitinspector uses JavaScript for pie chart outputs.

**Comment by adam-waldenberg** [comment]
Closing. Originally reported issue does not make any sense.
