### ISSUE TITLE
Add information regarding modified, deleted or new lines of code

### ISSUE THREAD

**Issue by vivuoren** [ejwa/gitinspector#176]
Timeline feature is very usefull and you can get valuable data regarding a certain period of time. But to get even more detailed what each contributor has done during this period it would be useful to know:
-New lines of code per person.
-Modified lines per person.
-Deleted lines per person.
-List of modified files per person.

After each period there is the total number of code lines changed during the time. For this total count the same information would be useful:
-Total count of new code lines.
-Total count of deleted code lines.
-Total count of modified code lines.
-List of all modified files.

Below you can see the current output and proposed output.

Current output:
        "timeline": {
            "message": "The following history timeline has been gathered from the repository",
            "period_length": "week",
            "periods": [
            {
                "name": "2017W01",
                "authors": [
                {
                    "name": "Doe John",
                    "email": "john.doe@doeland.com",
                    "gravatar": "https://www.gravatar.com/avatar/1234567890?default=identicon",
                    "work": "+++++++++++++++++++++++++++++"

Proposed output:
        "timeline": {
            "message": "The following history timeline has been gathered from the repository",
            "period_length": "week",
            "periods": [
            {
                "name": "2017W01",
                "authors": [
                {
                    "name": "Doe John",
                    "email": "john.doe@doeland.com",
                    "gravatar": "https://www.gravatar.com/avatar/1234567890?default=identicon",
                    "new_lines": 44
                    "modified_lines": 13
                    "deleted_lines": 20
                    "affected_files": src\feature1\file1.cs,src\feature2\file1.cs,src\config\conf1.conf
                    "work": "+++++++++++++++++++++++++++++"

**Comment by adam-waldenberg** [comment]
Hi. Sorry for the slow answer. I had a lot to do lately and maintenance of gitinspector has slipped behind slightly.

The problem with the proposal is that gitinspector is intended to give you a good overview... This is why a total lines of code and a percentage (work and number of pluses/minuses) was chosen. How do we visualize this data in the console and/or HTML output ?

Your example works for json and xml... But I don't see how we can cleanly get it visualized in the other modes.

**Comment by adam-waldenberg** [comment]
Closing this, as getting it cleanly integrated into any of the other output modes seems quite difficult.
