### ISSUE TITLE
Example outputs no longer working

### ISSUE THREAD

**Issue by robert-skarzycki** [ejwa/gitinspector#178]
Hi,

FYI - example output links provided on the README redirects to some unexpected page.

P.S. Consider hosting those pages on the free app server like Heroku.

**Comment by adam-waldenberg** [comment]
Hi @robert-skarzycki.

Duplicate of #172.

I own a data center and a hosting service, so using some free alternative is out of the question. With that being said, the reason for the redirection is that I had to reinstall and resecure that server some time ago and have not gotten around installing the service that hosts the gitinspector examples.

I will look into it once I have time.
