### ISSUE TITLE
add option to merge explicitely listed user groups

### ISSUE THREAD

**Issue by typekpb** [ejwa/gitinspector#181]
We have a repo, where users has changed their names. I'd love to see the feature to merge the explicitly listed user groups (via some command line switch) into ones => to have the real-user stats.
Any chance for that?

**Comment by adam-waldenberg** [comment]
@typekpb No need for this in gitinspector. See for example #174, #151, #131, #105, #74. There are probably even more issues, discussing this, but you get the idea. More information on merging authors (or changing their names) is available in the [FAQ](https://github.com/ejwa/gitinspector/wiki/FAQ).

**Comment by typekpb** [comment]
It works! Thank you.
