### ISSUE TITLE
getting warning messages related to diff.renameLimit

### ISSUE THREAD

**Issue by yogesh9391** [ejwa/gitinspector#189]
I am getting following warning messages while running gitinspector on my git branch.  

> warning: only found copies from modified paths due to too many files.   
    warning: you may want to set your diff.renameLimit variable to at least 3771 and retry the command.  gitinspector version is `0.5.0`.   Also, the reports are also not correct.  Is it affecting to the reports? if yes, does anyone knows fix for it??

**Comment by adam-waldenberg** [comment]
Hi @yogesh9391

This is related to git, not gitinspector. From the git documentation,

```diff.renameLimit
The number of files to consider when performing the copy/rename detection; equivalent to the 'git diff' option -l. This setting has no effect if rename detection is turned off.```

And yes, it does affect your git history (and you diff's), so you need to increase this particular config parameter if you happen to exceed it.

Closing.
