### ISSUE TITLE
-h,--help fails if not in a valid repository

### ISSUE THREAD

**Issue by andoalon** [ejwa/gitinspector#192]
Running the program with `-h` or `--help` does not display the help if a valid git repository is not found. Instead of displaying the help the program prints an error saying no repository was found and exits.
I think the program should output the help regardless, and not display the error
![image](https://user-images.githubusercontent.com/25222137/50115402-8f341700-0247-11e9-87a0-cd7291ef87d5.png)

**Comment by adam-waldenberg** [comment]
This is a duplicate of #177 and only affects master. Please refer to that issue for more information.
