### ISSUE TITLE
Pair programming support

### ISSUE THREAD

**Issue by piffy** [ejwa/gitinspector#195]
The program does not recognize at all the recent PP addition to github, i.e. joint commits. Mostly explpained here

https://hackernoon.com/power-up-your-pair-programming-with-co-authored-commits-on-github-ffb5d049aed3

**Comment by adam-waldenberg** [comment]
Co-authored-by is not handled by git in any way. So it would be impossible to track any statistics in any coherent or clean way. Closing.
