### ISSUE TITLE
Get cyclomatic complexity metrics for all files

### ISSUE THREAD

**Issue by emilppp** [ejwa/gitinspector#196]
Hi! :)

Is there any way to get cyclomatic complexity metrics for all files, not only the elevated ones? I want to get an average cyclomatic complexity across all files in a project.

**Comment by adam-waldenberg** [comment]
Hi @emilppp. You can edit metrics.py and play with the constants;
```
METRIC_CYCLOMATIC_COMPLEXITY_THRESHOLD
METRIC_CYCLOMATIC_COMPLEXITY_DENSITY_THRESHOLD
```
These specify the required value needed for the metric to be considered elevated. Set them to zero and you should get it for all files.
