### ISSUE TITLE
Pip package requirements

### ISSUE THREAD

**Issue by iranzo** [ejwa/gitinspector#198]
When trying to pip install the package it fails because of missing 'requirements.txt'

- localization
- numpy
- scipy
- shapely

(later it fails because of possible wrong code like localization.init, etc)

**Comment by adam-waldenberg** [comment]
We don't support PIP. The method of install is to use setup.py and setuptools or a derivate. If you want PIP support, please provide a pull request.

**Comment by iranzo** [comment]
Package is provided at pypi: https://pypi.org/project/gitinspector/  

So I would expect it to install natively with pip, and if not taken down

**Comment by adam-waldenberg** [comment]
@iranzo Anybody can put packages up on pypi. You should contact the maintainer of that package. Also, that version is very, very old.
