### ISSUE TITLE
Translation to Italian

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ejwa/gitinspector#20]
```
Translation to Italian attached as .po file.
```

Original issue reported on code.google.com by `lucamot` on 12 Nov 2013 at 10:05

Attachments:
* [messages_it.po](https://storage.googleapis.com/google-code-attachments/gitinspector/issue-20/comment-0/messages_it.po)

**Comment by adam-waldenberg** [comment]
Hi. A new messages.pot has been added with commit 47b11ad, so an update is needed to the translation file. Refer to the commit diff to see all changes.

Once updated, the translation can be included in the upcoming 0.4.2 release.

**Comment by adam-waldenberg** [comment]
Updated with commits pull request #2 and commits 58a983ed2710581dfed2caf14da418b254f7a827 and 8a0ba3dca1884e2460af68af34b39d7b2eaceab3.
