### ISSUE TITLE
port gitinspector to Python 3

### ISSUE THREAD

**Issue by sandrotosi** [ejwa/gitinspector#201]
in order to switch the debian package to python3, i ran 2to3 on gitinspector source code and adjust a few smaller issues (tabs vs spaces, 2to3 mistakes) and verified the tool still works. attached is the patch i used (based on 0.4.4)

[port-to-python3.patch.txt](https://github.com/ejwa/gitinspector/files/3659102/port-to-python3.patch.txt)

**Comment by adam-waldenberg** [comment]
Python3 is already supported. Closing.

**Comment by sandrotosi** [comment]
so maybe you want to release a new version, the last release if from 2016......

**Comment by adam-waldenberg** [comment]
Yes. When I have time to implement the planned features for 0.5.0, I will. Currently though I have a full schedule with a few other projects.

**Comment by ankostis** [comment]
Then please, re-open this issue, to keep an eye on the port (or accept PRs).

**Comment by ankostis** [comment]
Sorry, just discovered #213 (or #216) was the culprit, not python-3 incompatibility in general.

**Comment by adam-waldenberg** [comment]
@ankostis  No... But it does need some updates to be compatible with some recent API changes. I need to be sure I don't break backward compatibility, though - Worst case I'll just catch the exceptions and try different calls.
