### ISSUE TITLE
Brazilian Portuguese translation

### ISSUE THREAD

**Issue by iggar** [ejwa/gitinspector#202]
Hello, 
I'm a native Brazilian Portuguese speaker, had experience translating apps before and I would love to collaborate and add that support.

**Comment by adam-waldenberg** [comment]
Hi @iggar. That would be great, as long as you are willing to maintain it. Just create a pull request and I'll look at it :)

**Comment by adam-waldenberg** [comment]
No additional news on this, so closing.
