### ISSUE TITLE
Similar to --exclude, add an --include option

### ISSUE THREAD

**Issue by danieldietsch** [ejwa/gitinspector#205]
It would be nice if one could specify which paths to include in stat generation, and simply exclude everything else.

**Comment by adam-waldenberg** [comment]
Already available via regular expressions.
See https://github.com/ejwa/gitinspector/wiki/Documentation#filtering

**Comment by danieldietsch** [comment]
So you mean if I only wanted to include things from ``projectname/`` I would add 
``-x "file:^(projectname/)"`` as flag?
