### ISSUE TITLE
Ability to combine different names of the same author under the same person stats

### ISSUE THREAD

**Issue by iongion** [ejwa/gitinspector#222]
In old projects where git configuration has changed over time, it is more fair to combine authors that are the same person, but using different git configuration, example:

```
ion gion
Ion Gion
gion ion
```

Are the same person

**Comment by adam-waldenberg** [comment]
This is a feature in git and does not belong in gitinspector - there are issues about this on the tracker. It's also covered in the https://github.com/ejwa/gitinspector/wiki/FAQ

**Comment by iongion** [comment]
Thank you @adam-waldenberg - quite useful
