### ISSUE TITLE
Support for multiple repositories

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ejwa/gitinspector#24]
```
I would like gitinspector to be able to generate a combined report for multiple 
git repositories.
```

Original issue reported on code.google.com by `lapoussi...@gmail.com` on 2 Feb 2014 at 5:25

**Comment by diwu1989** [comment]
I really need this feature too, looking forward to this.

**Comment by adam-waldenberg** [comment]
This has been postponed for 5.0 because the feature needs some refactoring to the code before this can be implemented in a proper and clean way. After 0.4.x development is done, this feature will be the next thing added together with a new responsive HTML output based on Bootstrap.

**Comment by dzhus** [comment]
Cool. I am the original reporter, keeping an eye on this.

**Comment by adam-waldenberg** [comment]
Work on this has slowly begun.

**Comment by adam-waldenberg** [comment]
Almost done.

Current issues:
* It only prints out the name of the last repository specified.
* "-m" metrics is missing support for this right now. 
* Progress output does not specify which repo is currently being processed.

Please test this with filtering and all the other features of gitinspector and check that it behaves as you would expect.

**Comment by adam-waldenberg** [comment]
The -m flag (and metrics module) is now functional with multiple repositories.

**Comment by adam-waldenberg** [comment]
The name of all the repositories should now be properly printed to stdout when generating a report.

**Comment by adam-waldenberg** [comment]
I now consider this feature fully implemented, please report any problems in a new issue.

**Comment by yogesh9391** [comment]
Hey adam-waldenberg,
Can you please provide whole command to use for multiple repositories? I have following command for me.   
`python /opt/gitinspector/gitinspector.py -HTlr --grading --file-types=sh,yml,yaml,py,conf --format=htmlembedded  <repo1_path> <repo2_path>  > output.html`   
How should I use `-m` option incase of multiple repos ??

**Comment by yogesh9391** [comment]
Thanks Adam.
I was using .0.4. I will try with version .0.5

**Comment by yogesh9391** [comment]
Hi Adam,
Back again :(
I am able to generate consolidated report successfully. However, this report has all the others from all the repos making it difficult to segregate them. Any option for this? means Any way to identify relationship between author and repository.

**Comment by adam-waldenberg** [comment]
@yogesh9391 Sorry. I completely missed this comment.

No, there is no way to see what came from what repo. The way to do this is to run gitinspector separately on each individual repo and then run a merged report to get a summary.
