### ISSUE TITLE
Gitinspector does not look at the css, fxml and csv files in the resource folder

### ISSUE THREAD

**Issue by enterprisennew** [ejwa/gitinspector#240]
At the moment I am creating a foodapp with Java, I have created a java project and the gitinspector only looks at the data that is in the java folder, at intelij.

I have fxml, css, md, csvand cmd files in the resource folder, unfortunately these are not looked at.

Why are the files in the resource folder not counted?

The files are not listen in the gitinspector.

**Comment by adam-waldenberg** [comment]
This is what -f is for.

https://github.com/ejwa/gitinspector/wiki/Documentation
