### ISSUE TITLE
Translation to German

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ejwa/gitinspector#25]
```
Hello, 

on the main page it says "Translators wanted". I'd be willing to offer a German 
translation for this project, as I quite like it and would love to have the 
output in German. 

In https://code.google.com/p/gitinspector/wiki/Contributing it says to just 
open a new issue for a translation, but sadly it does not tell about how to 
translate. I've already seen some existing translations, but can't figure out 
what the non-plaintext file is. 

I also tried finding previous translation issues, but was unable to find any.

So, if there is need for a German translation, please provide instructions on 
how to translate.

--


```

Original issue reported on code.google.com by `supertu...@gmail.com` on 9 Feb 2014 at 2:17

**Comment by adam-waldenberg** [comment]
Hi. A new messages.pot has been added with commit 47b11ad, so an update is needed to the translation file. Refer to the commit diff to see all changes.

Once updated, the translation can be included in the upcoming 0.4.2 release.

**Comment by xxyy** [comment]
I will see if I can find time to update the translation for the release, don't count on it though.

**Comment by adam-waldenberg** [comment]
Hi. No worries. Do it when you have time available. We can always make an extra 0.4.3 release for any translations that don't make it into 0.4.2.
