### ISSUE TITLE
Support for comments/metrics in C# code

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ejwa/gitinspector#59]
```
Apologies in advance if this is not the appropriate venue for questions...

Does gitinspector work for repositories containing .Net code (specifically C#, 
*.cs files)?
How about Windows PowerShell code (*.ps1, *.psm1)?
```

Original issue reported on code.google.com by `jrnai...@gmail.com` on 19 Feb 2015 at 5:03

**Comment by adam-waldenberg** [comment]
I decided to skip the PowerShell part of this issue. It does not feel as important as the C# support. Furthermore, I don't have a good grasp on it.

**Comment by carloreggiani** [comment]
I'm trying to use gitinspector for COBOL language, but I'm feeling alone :(

Any support?

**Comment by adam-waldenberg** [comment]
It's not supported, no. However, it should be easy enough to add. Again, patches/pull requests are welcome.
