### ISSUE TITLE
Merge same author with diffenent names.

### ISSUE THREAD

**Issue by luckydonald** [ejwa/gitinspector#74]
Is there already an option for this I missed?

**Comment by adam-waldenberg** [comment]
There is a .mailmap fie. Please refer to the [FAQ](FAQ).

**Comment by luckydonald** [comment]
Working Link: [FAQ](https://github.com/ejwa/gitinspector/wiki/FAQ) 

-------
Oh It is even the first entry. Okey. Sorry. :sweat_smile:
