### ISSUE TITLE
Inaccurate output

### ISSUE THREAD

**Issue by kosta-tachtevrenidis** [ejwa/gitinspector#75]
It is entirely possible, I don't understand how stats are calculated. When I run 'git shortlog -sne', the number of commits vary WILDLY from when I run gitinspector (I am not specifying any time interval, trying to get stats for the entire lifetime of the branch). For the same user, git shortlog shows 317 commits while gitinspector shows 3. What am I missing?

**Comment by adam-waldenberg** [comment]
Hi.

Gitinspector also tries to merge authors independently from .mailmap. If you, for example, use different auhor names. between differen commits.

So:
> Kalle kalle@kalle.com

is the same as:

> Nisse @kall@.com

**Comment by adam-waldenberg** [comment]
Hi.

Gitinspector also tries to merge authors independently from .mailmap. If you, for example, use different auhor names. between differen commits.

So:
> Kalle kalle@kalle.com

is the same as:

> Nisse @kall@.com

**Comment by kosta-tachtevrenidis** [comment]
ok I made sure there are no duplicate personas.

**Comment by adam-waldenberg** [comment]
Going ahead and marking as invalid. Please notify if there is an update on this issue.

**Comment by kosta-tachtevrenidis** [comment]
Adam, why did you close as invalid? What info can I provide to help troubleshoot? As I said the git shortlog and gitinspector are wildly different.

**Comment by adam-waldenberg** [comment]
Because I'm fairly certain there's nothing wrong here. What happens if you do something like

gitinspector.py -f "**"

and compare that to the shortlog ?

**Comment by adam-waldenberg** [comment]
Checking in to see if there's any news on this ? Did my suggestions help ?

**Comment by kosta-tachtevrenidis** [comment]
sorry for the delay, I am traveling this week. Hope to try it out next week :-)

**Comment by adam-waldenberg** [comment]
Added a new entry to the [FAQ](https://github.com/ejwa/gitinspector/wiki/FAQ) concerning this. Hope it helps.

**Comment by adam-waldenberg** [comment]
As there has been no update for a while, I'm closing this as invalid.
