### ISSUE TITLE
Include author email in JSON and HTML outputs.

### ISSUE THREAD

**Issue by suhasxavier** [ejwa/gitinspector#85]
The json response contains an "authors" array which displays user's first and last name but there is no mention of the github username. Can this also be included in the response?

**Comment by adam-waldenberg** [comment]
No. Direct GitHub support is outside the scope of gitinspector; it's intended to be independent and should not depend on a hosting service. However, we could include the email in the response. Gitinspector tries to keep track of authors and their "latest" email address. That email could be included.

You can then use something like;
https://github.com/sindresorhus/github-username
... to fetch the GitHub username.

**Comment by adam-waldenberg** [comment]
Changing the header of the issue.

**Comment by adam-waldenberg** [comment]
Implemented. Report any problems in a fresh issue.

**Comment by suhasxavier** [comment]
Works great! Thanks!
