### ISSUE TITLE
Support for robotframework(.robot) files

### ISSUE THREAD

**Issue by huangzhizhong** [ejwa/gitinspector#88]

**Comment by adam-waldenberg** [comment]
@huangzhizhong 

Comments are easy.. However, I'm not so sure about the metrics... I personally don't use it regularly. Is there a language grammar available somewhere?

**Comment by huangzhizhong** [comment]
see also http://robotframework.org/, and [cloc](http://cloc.sourceforge.net/) has supported it, which is listed in http://cloc.sourceforge.net/#Languages

**Comment by adam-waldenberg** [comment]
Removing tsv from the description, as that is a completely different format. Added a separate issue for this with issue #89.

**Comment by adam-waldenberg** [comment]
If someone needs this one, please provide a pull requests. Closing for now.
