### ISSUE TITLE
Locale errors

### ISSUE THREAD

**Issue by max-mykhailenko** [ejwa/gitinspector#93]
OSX problem with locale can be resolved by adding to `~/.profile` or `~/.bash_profile`
```
export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8
```

**Comment by adam-waldenberg** [comment]
Yes. This is a known "bug"in OS X in conjunction with  any application that has locale support using gettext. Covered in issues #32 and #54 (amongst others).

Maybe it's time for a wiki document covering different problems that can be encountered with different OS's. I'll look into that eventually... Most of the strange issues encountered are (most of the time) directly related to Windows installations.
