### ISSUE TITLE
Configurable concurrency

### ISSUE THREAD

**Issue by imposeren** [ejwa/gitinspector#96]
https://github.com/ejwa/gitinspector/issues/22#issuecomment-165788269 by @adam-waldenberg 
> Gitinspector starts as many processes as there are threads/cores. There is no configuration option for it, and never will be. However, there is a constant at the top of changes.py and blame.py that controls the number of threads.

Why there will never be such an option? I think that it's not hard to implement such an option. I was planning to submit pull request for this. What are the reasons against such an option?

Example
```sh
gitinspector --concurrency=2 ...
```

**Comment by adam-waldenberg** [comment]
@imposeren 

The reason is that it's generally something that should be automatic. If the use case is to lower the impact on the system it's generally a better solution to just renice gitinspector and it's sub-processes.

**Comment by adam-waldenberg** [comment]
@imposeren 

I don't know what system you are on... If it's a unix variant you can do something like;

nice -n15 ./gitinspector.py <options>

... and you should be in business.

**Comment by adam-waldenberg** [comment]
There's no compelling argument for this feature, so I'm closing this.
